[server]
port = "8080"
mode = "debug"

[database]
name = "root/data/iano_chat.db"
max_open_conns = 25
max_idle_conns = 5

[jwt]
secret = "your-secret-key"
expire_hours = 24

[log]
level = "info"
format = "json"
path = "root/logs/app.log"
max_size = 100
max_backups = 30
max_age = 7
compress = true
